list_of_tickers = ['ETHUSDT', 'XMRUSDT', 'LTCUSDT', 'ZECUSDT']
# list_of_tickers = ['ZECUSDT','XRPUSDT', 'MATICUSDT', 'ALGOUSDT','BATUSDT', 'RENUSDT', 'ADAUSDT', 'AVAXUSDT', 'ETHUSDT', 'BNBUSDT','XMRUSDT']
